/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface VmwareVirtualDisk {
  id?: string;
  createdAt?: object;
  updatedAt?: object;
  readonly version?: number;
  deletedAt?: object;
  name: string;
  description?: string;
  diskSize: number;
  rawLun: boolean;
  rawLunId: number;
  virtualMachineId: string;
}
