export * from './v1Appliances.service';
import { V1AppliancesService } from './v1Appliances.service';
export * from './v1Auth.service';
import { V1AuthService } from './v1Auth.service';
export * from './v1ConfigurationUpload.service';
import { V1ConfigurationUploadService } from './v1ConfigurationUpload.service';
export * from './v1Datacenters.service';
import { V1DatacentersService } from './v1Datacenters.service';
export * from './v1Jobs.service';
import { V1JobsService } from './v1Jobs.service';
export * from './v1LoadBalancerHealthMonitors.service';
import { V1LoadBalancerHealthMonitorsService } from './v1LoadBalancerHealthMonitors.service';
export * from './v1LoadBalancerIrules.service';
import { V1LoadBalancerIrulesService } from './v1LoadBalancerIrules.service';
export * from './v1LoadBalancerNodes.service';
import { V1LoadBalancerNodesService } from './v1LoadBalancerNodes.service';
export * from './v1LoadBalancerPolicies.service';
import { V1LoadBalancerPoliciesService } from './v1LoadBalancerPolicies.service';
export * from './v1LoadBalancerPools.service';
import { V1LoadBalancerPoolsService } from './v1LoadBalancerPools.service';
export * from './v1LoadBalancerProfiles.service';
import { V1LoadBalancerProfilesService } from './v1LoadBalancerProfiles.service';
export * from './v1LoadBalancerRoutes.service';
import { V1LoadBalancerRoutesService } from './v1LoadBalancerRoutes.service';
export * from './v1LoadBalancerSelfIps.service';
import { V1LoadBalancerSelfIpsService } from './v1LoadBalancerSelfIps.service';
export * from './v1LoadBalancerVirtualServers.service';
import { V1LoadBalancerVirtualServersService } from './v1LoadBalancerVirtualServers.service';
export * from './v1LoadBalancerVlans.service';
import { V1LoadBalancerVlansService } from './v1LoadBalancerVlans.service';
export * from './v1NetworkSecurityFirewallRuleGroups.service';
import { V1NetworkSecurityFirewallRuleGroupsService } from './v1NetworkSecurityFirewallRuleGroups.service';
export * from './v1NetworkSecurityFirewallRules.service';
import { V1NetworkSecurityFirewallRulesService } from './v1NetworkSecurityFirewallRules.service';
export * from './v1NetworkSecurityNetworkObjectGroups.service';
import { V1NetworkSecurityNetworkObjectGroupsService } from './v1NetworkSecurityNetworkObjectGroups.service';
export * from './v1NetworkSecurityNetworkObjects.service';
import { V1NetworkSecurityNetworkObjectsService } from './v1NetworkSecurityNetworkObjects.service';
export * from './v1NetworkSecurityServiceObjectGroups.service';
import { V1NetworkSecurityServiceObjectGroupsService } from './v1NetworkSecurityServiceObjectGroups.service';
export * from './v1NetworkSecurityServiceObjects.service';
import { V1NetworkSecurityServiceObjectsService } from './v1NetworkSecurityServiceObjects.service';
export * from './v1NetworkStaticRoutes.service';
import { V1NetworkStaticRoutesService } from './v1NetworkStaticRoutes.service';
export * from './v1NetworkSubnets.service';
import { V1NetworkSubnetsService } from './v1NetworkSubnets.service';
export * from './v1NetworkVlans.service';
import { V1NetworkVlansService } from './v1NetworkVlans.service';
export * from './v1PhysicalServers.service';
import { V1PhysicalServersService } from './v1PhysicalServers.service';
export * from './v1PriorityGroups.service';
import { V1PriorityGroupsService } from './v1PriorityGroups.service';
export * from './v1TierGroups.service';
import { V1TierGroupsService } from './v1TierGroups.service';
export * from './v1Tiers.service';
import { V1TiersService } from './v1Tiers.service';
export * from './v1Vlans.service';
import { V1VlansService } from './v1Vlans.service';
export * from './v1VmwareNetworkAdapter.service';
import { V1VmwareNetworkAdapterService } from './v1VmwareNetworkAdapter.service';
export * from './v1VmwareVirtualDisks.service';
import { V1VmwareVirtualDisksService } from './v1VmwareVirtualDisks.service';
export * from './v1VmwareVirtualMachines.service';
import { V1VmwareVirtualMachinesService } from './v1VmwareVirtualMachines.service';
export * from './v1Vts.service';
import { V1VtsService } from './v1Vts.service';
export const APIS = [V1AppliancesService, V1AuthService, V1ConfigurationUploadService, V1DatacentersService, V1JobsService, V1LoadBalancerHealthMonitorsService, V1LoadBalancerIrulesService, V1LoadBalancerNodesService, V1LoadBalancerPoliciesService, V1LoadBalancerPoolsService, V1LoadBalancerProfilesService, V1LoadBalancerRoutesService, V1LoadBalancerSelfIpsService, V1LoadBalancerVirtualServersService, V1LoadBalancerVlansService, V1NetworkSecurityFirewallRuleGroupsService, V1NetworkSecurityFirewallRulesService, V1NetworkSecurityNetworkObjectGroupsService, V1NetworkSecurityNetworkObjectsService, V1NetworkSecurityServiceObjectGroupsService, V1NetworkSecurityServiceObjectsService, V1NetworkStaticRoutesService, V1NetworkSubnetsService, V1NetworkVlansService, V1PhysicalServersService, V1PriorityGroupsService, V1TierGroupsService, V1TiersService, V1VlansService, V1VmwareNetworkAdapterService, V1VmwareVirtualDisksService, V1VmwareVirtualMachinesService, V1VtsService];
