/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { Appliance } from '../model/appliance';
import { GeneratedApplianceBulkDto } from '../model/generatedApplianceBulkDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


export interface V1AppliancesBulkPostRequestParams {
    generatedApplianceBulkDto: GeneratedApplianceBulkDto;
}

export interface V1AppliancesGetRequestParams {
    fields?: string;
    filter?: string;
    or?: string;
    sort?: string;
    join?: string;
    perPage?: number;
    offset?: number;
    page?: number;
    cache?: number;
}

export interface V1AppliancesIdDeleteRequestParams {
    id: string;
}

export interface V1AppliancesIdGetRequestParams {
    id: string;
    fields?: string;
    join?: string;
    cache?: number;
}

export interface V1AppliancesIdPatchRequestParams {
    id: string;
    appliance: Appliance;
}

export interface V1AppliancesIdPutRequestParams {
    id: string;
    appliance: Appliance;
}

export interface V1AppliancesIdRestorePatchRequestParams {
    id: string;
}

export interface V1AppliancesIdSoftDeleteRequestParams {
    id: string;
}

export interface V1AppliancesPostRequestParams {
    appliance: Appliance;
}


@Injectable({
  providedIn: 'root'
})
export class V1AppliancesService {

    protected basePath = 'http://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Create many Appliance
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesBulkPost(requestParameters: V1AppliancesBulkPostRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<Appliance>>;
    public v1AppliancesBulkPost(requestParameters: V1AppliancesBulkPostRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Appliance>>>;
    public v1AppliancesBulkPost(requestParameters: V1AppliancesBulkPostRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Appliance>>>;
    public v1AppliancesBulkPost(requestParameters: V1AppliancesBulkPostRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const generatedApplianceBulkDto = requestParameters.generatedApplianceBulkDto;
        if (generatedApplianceBulkDto === null || generatedApplianceBulkDto === undefined) {
            throw new Error('Required parameter generatedApplianceBulkDto was null or undefined when calling v1AppliancesBulkPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<Appliance>>(`${this.configuration.basePath}/v1/appliances/bulk`,
            generatedApplianceBulkDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve many Appliance
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesGet(requestParameters: V1AppliancesGetRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<Appliance>>;
    public v1AppliancesGet(requestParameters: V1AppliancesGetRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Appliance>>>;
    public v1AppliancesGet(requestParameters: V1AppliancesGetRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Appliance>>>;
    public v1AppliancesGet(requestParameters: V1AppliancesGetRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const fields = requestParameters.fields;
        const filter = requestParameters.filter;
        const or = requestParameters.or;
        const sort = requestParameters.sort;
        const join = requestParameters.join;
        const perPage = requestParameters.perPage;
        const offset = requestParameters.offset;
        const page = requestParameters.page;
        const cache = requestParameters.cache;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }
        if (or !== undefined && or !== null) {
            queryParameters = queryParameters.set('or', <any>or);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join', <any>join);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page', <any>perPage);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache', <any>cache);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<Appliance>>(`${this.configuration.basePath}/v1/appliances`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete one Appliance
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesIdDelete(requestParameters: V1AppliancesIdDeleteRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public v1AppliancesIdDelete(requestParameters: V1AppliancesIdDeleteRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public v1AppliancesIdDelete(requestParameters: V1AppliancesIdDeleteRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public v1AppliancesIdDelete(requestParameters: V1AppliancesIdDeleteRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1AppliancesIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<Appliance>(`${this.configuration.basePath}/v1/appliances/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one Appliance
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesIdGet(requestParameters: V1AppliancesIdGetRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public v1AppliancesIdGet(requestParameters: V1AppliancesIdGetRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public v1AppliancesIdGet(requestParameters: V1AppliancesIdGetRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public v1AppliancesIdGet(requestParameters: V1AppliancesIdGetRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1AppliancesIdGet.');
        }
        const fields = requestParameters.fields;
        const join = requestParameters.join;
        const cache = requestParameters.cache;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join', <any>join);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache', <any>cache);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Appliance>(`${this.configuration.basePath}/v1/appliances/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update one Appliance
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesIdPatch(requestParameters: V1AppliancesIdPatchRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public v1AppliancesIdPatch(requestParameters: V1AppliancesIdPatchRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public v1AppliancesIdPatch(requestParameters: V1AppliancesIdPatchRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public v1AppliancesIdPatch(requestParameters: V1AppliancesIdPatchRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1AppliancesIdPatch.');
        }
        const appliance = requestParameters.appliance;
        if (appliance === null || appliance === undefined) {
            throw new Error('Required parameter appliance was null or undefined when calling v1AppliancesIdPatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<Appliance>(`${this.configuration.basePath}/v1/appliances/${encodeURIComponent(String(id))}`,
            appliance,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Replace one Appliance
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesIdPut(requestParameters: V1AppliancesIdPutRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public v1AppliancesIdPut(requestParameters: V1AppliancesIdPutRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public v1AppliancesIdPut(requestParameters: V1AppliancesIdPutRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public v1AppliancesIdPut(requestParameters: V1AppliancesIdPutRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1AppliancesIdPut.');
        }
        const appliance = requestParameters.appliance;
        if (appliance === null || appliance === undefined) {
            throw new Error('Required parameter appliance was null or undefined when calling v1AppliancesIdPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Appliance>(`${this.configuration.basePath}/v1/appliances/${encodeURIComponent(String(id))}`,
            appliance,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restores a Soft-Deleted Entity.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesIdRestorePatch(requestParameters: V1AppliancesIdRestorePatchRequestParams, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v1AppliancesIdRestorePatch(requestParameters: V1AppliancesIdRestorePatchRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v1AppliancesIdRestorePatch(requestParameters: V1AppliancesIdRestorePatchRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v1AppliancesIdRestorePatch(requestParameters: V1AppliancesIdRestorePatchRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1AppliancesIdRestorePatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.patch<any>(`${this.configuration.basePath}/v1/appliances/${encodeURIComponent(String(id))}/restore`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Soft deletes an Entity.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesIdSoftDelete(requestParameters: V1AppliancesIdSoftDeleteRequestParams, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v1AppliancesIdSoftDelete(requestParameters: V1AppliancesIdSoftDeleteRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v1AppliancesIdSoftDelete(requestParameters: V1AppliancesIdSoftDeleteRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v1AppliancesIdSoftDelete(requestParameters: V1AppliancesIdSoftDeleteRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1AppliancesIdSoftDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<any>(`${this.configuration.basePath}/v1/appliances/${encodeURIComponent(String(id))}/soft`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create one Appliance
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1AppliancesPost(requestParameters: V1AppliancesPostRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public v1AppliancesPost(requestParameters: V1AppliancesPostRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public v1AppliancesPost(requestParameters: V1AppliancesPostRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public v1AppliancesPost(requestParameters: V1AppliancesPostRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const appliance = requestParameters.appliance;
        if (appliance === null || appliance === undefined) {
            throw new Error('Required parameter appliance was null or undefined when calling v1AppliancesPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Appliance>(`${this.configuration.basePath}/v1/appliances`,
            appliance,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
