/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { GeneratedLoadBalancerVirtualServerBulkDto } from '../model/generatedLoadBalancerVirtualServerBulkDto';
import { LoadBalancerVirtualServer } from '../model/loadBalancerVirtualServer';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


export interface V1LoadBalancerVirtualServersBulkPostRequestParams {
    generatedLoadBalancerVirtualServerBulkDto: GeneratedLoadBalancerVirtualServerBulkDto;
}

export interface V1LoadBalancerVirtualServersGetRequestParams {
    fields?: string;
    filter?: string;
    or?: string;
    sort?: string;
    join?: string;
    perPage?: number;
    offset?: number;
    page?: number;
    cache?: number;
}

export interface V1LoadBalancerVirtualServersIdDeleteRequestParams {
    id: string;
}

export interface V1LoadBalancerVirtualServersIdDeprovisionPatchRequestParams {
    id: string;
}

export interface V1LoadBalancerVirtualServersIdGetRequestParams {
    id: string;
    fields?: string;
    join?: string;
    cache?: number;
}

export interface V1LoadBalancerVirtualServersIdPatchRequestParams {
    id: string;
    loadBalancerVirtualServer: LoadBalancerVirtualServer;
}

export interface V1LoadBalancerVirtualServersIdProvisionPutRequestParams {
    id: string;
}

export interface V1LoadBalancerVirtualServersIdPutRequestParams {
    id: string;
    loadBalancerVirtualServer: LoadBalancerVirtualServer;
}

export interface V1LoadBalancerVirtualServersIdRestorePatchRequestParams {
    id: string;
}

export interface V1LoadBalancerVirtualServersIdSoftDeleteRequestParams {
    id: string;
}

export interface V1LoadBalancerVirtualServersPostRequestParams {
    loadBalancerVirtualServer: LoadBalancerVirtualServer;
}

export interface V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDeleteRequestParams {
    virtualServerId: string;
    iruleId: string;
}

export interface V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPostRequestParams {
    virtualServerId: string;
    iruleId: string;
}

export interface V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDeleteRequestParams {
    virtualServerId: string;
    profileId: string;
}

export interface V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPostRequestParams {
    virtualServerId: string;
    profileId: string;
}


@Injectable({
  providedIn: 'root'
})
export class V1LoadBalancerVirtualServersService {

    protected basePath = 'http://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Create many LoadBalancerVirtualServer
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersBulkPost(requestParameters: V1LoadBalancerVirtualServersBulkPostRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersBulkPost(requestParameters: V1LoadBalancerVirtualServersBulkPostRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LoadBalancerVirtualServer>>>;
    public v1LoadBalancerVirtualServersBulkPost(requestParameters: V1LoadBalancerVirtualServersBulkPostRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LoadBalancerVirtualServer>>>;
    public v1LoadBalancerVirtualServersBulkPost(requestParameters: V1LoadBalancerVirtualServersBulkPostRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const generatedLoadBalancerVirtualServerBulkDto = requestParameters.generatedLoadBalancerVirtualServerBulkDto;
        if (generatedLoadBalancerVirtualServerBulkDto === null || generatedLoadBalancerVirtualServerBulkDto === undefined) {
            throw new Error('Required parameter generatedLoadBalancerVirtualServerBulkDto was null or undefined when calling v1LoadBalancerVirtualServersBulkPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<LoadBalancerVirtualServer>>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/bulk`,
            generatedLoadBalancerVirtualServerBulkDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve many LoadBalancerVirtualServer
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersGet(requestParameters: V1LoadBalancerVirtualServersGetRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersGet(requestParameters: V1LoadBalancerVirtualServersGetRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LoadBalancerVirtualServer>>>;
    public v1LoadBalancerVirtualServersGet(requestParameters: V1LoadBalancerVirtualServersGetRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LoadBalancerVirtualServer>>>;
    public v1LoadBalancerVirtualServersGet(requestParameters: V1LoadBalancerVirtualServersGetRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const fields = requestParameters.fields;
        const filter = requestParameters.filter;
        const or = requestParameters.or;
        const sort = requestParameters.sort;
        const join = requestParameters.join;
        const perPage = requestParameters.perPage;
        const offset = requestParameters.offset;
        const page = requestParameters.page;
        const cache = requestParameters.cache;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }
        if (or !== undefined && or !== null) {
            queryParameters = queryParameters.set('or', <any>or);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join', <any>join);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page', <any>perPage);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache', <any>cache);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<LoadBalancerVirtualServer>>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete one LoadBalancerVirtualServer
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersIdDelete(requestParameters: V1LoadBalancerVirtualServersIdDeleteRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersIdDelete(requestParameters: V1LoadBalancerVirtualServersIdDeleteRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersIdDelete(requestParameters: V1LoadBalancerVirtualServersIdDeleteRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersIdDelete(requestParameters: V1LoadBalancerVirtualServersIdDeleteRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1LoadBalancerVirtualServersIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deprovisions an Entity.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersIdDeprovisionPatch(requestParameters: V1LoadBalancerVirtualServersIdDeprovisionPatchRequestParams, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v1LoadBalancerVirtualServersIdDeprovisionPatch(requestParameters: V1LoadBalancerVirtualServersIdDeprovisionPatchRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v1LoadBalancerVirtualServersIdDeprovisionPatch(requestParameters: V1LoadBalancerVirtualServersIdDeprovisionPatchRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v1LoadBalancerVirtualServersIdDeprovisionPatch(requestParameters: V1LoadBalancerVirtualServersIdDeprovisionPatchRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1LoadBalancerVirtualServersIdDeprovisionPatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.patch<any>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(id))}/deprovision`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one LoadBalancerVirtualServer
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersIdGet(requestParameters: V1LoadBalancerVirtualServersIdGetRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersIdGet(requestParameters: V1LoadBalancerVirtualServersIdGetRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersIdGet(requestParameters: V1LoadBalancerVirtualServersIdGetRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersIdGet(requestParameters: V1LoadBalancerVirtualServersIdGetRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1LoadBalancerVirtualServersIdGet.');
        }
        const fields = requestParameters.fields;
        const join = requestParameters.join;
        const cache = requestParameters.cache;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join', <any>join);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache', <any>cache);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update one LoadBalancerVirtualServer
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersIdPatch(requestParameters: V1LoadBalancerVirtualServersIdPatchRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersIdPatch(requestParameters: V1LoadBalancerVirtualServersIdPatchRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersIdPatch(requestParameters: V1LoadBalancerVirtualServersIdPatchRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersIdPatch(requestParameters: V1LoadBalancerVirtualServersIdPatchRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1LoadBalancerVirtualServersIdPatch.');
        }
        const loadBalancerVirtualServer = requestParameters.loadBalancerVirtualServer;
        if (loadBalancerVirtualServer === null || loadBalancerVirtualServer === undefined) {
            throw new Error('Required parameter loadBalancerVirtualServer was null or undefined when calling v1LoadBalancerVirtualServersIdPatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(id))}`,
            loadBalancerVirtualServer,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Provisions an Entity.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersIdProvisionPut(requestParameters: V1LoadBalancerVirtualServersIdProvisionPutRequestParams, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v1LoadBalancerVirtualServersIdProvisionPut(requestParameters: V1LoadBalancerVirtualServersIdProvisionPutRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v1LoadBalancerVirtualServersIdProvisionPut(requestParameters: V1LoadBalancerVirtualServersIdProvisionPutRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v1LoadBalancerVirtualServersIdProvisionPut(requestParameters: V1LoadBalancerVirtualServersIdProvisionPutRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1LoadBalancerVirtualServersIdProvisionPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.put<any>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(id))}/provision`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Replace one LoadBalancerVirtualServer
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersIdPut(requestParameters: V1LoadBalancerVirtualServersIdPutRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersIdPut(requestParameters: V1LoadBalancerVirtualServersIdPutRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersIdPut(requestParameters: V1LoadBalancerVirtualServersIdPutRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersIdPut(requestParameters: V1LoadBalancerVirtualServersIdPutRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1LoadBalancerVirtualServersIdPut.');
        }
        const loadBalancerVirtualServer = requestParameters.loadBalancerVirtualServer;
        if (loadBalancerVirtualServer === null || loadBalancerVirtualServer === undefined) {
            throw new Error('Required parameter loadBalancerVirtualServer was null or undefined when calling v1LoadBalancerVirtualServersIdPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(id))}`,
            loadBalancerVirtualServer,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restores a Soft-Deleted Entity.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersIdRestorePatch(requestParameters: V1LoadBalancerVirtualServersIdRestorePatchRequestParams, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v1LoadBalancerVirtualServersIdRestorePatch(requestParameters: V1LoadBalancerVirtualServersIdRestorePatchRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v1LoadBalancerVirtualServersIdRestorePatch(requestParameters: V1LoadBalancerVirtualServersIdRestorePatchRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v1LoadBalancerVirtualServersIdRestorePatch(requestParameters: V1LoadBalancerVirtualServersIdRestorePatchRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1LoadBalancerVirtualServersIdRestorePatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.patch<any>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(id))}/restore`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Soft deletes an Entity.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersIdSoftDelete(requestParameters: V1LoadBalancerVirtualServersIdSoftDeleteRequestParams, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v1LoadBalancerVirtualServersIdSoftDelete(requestParameters: V1LoadBalancerVirtualServersIdSoftDeleteRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v1LoadBalancerVirtualServersIdSoftDelete(requestParameters: V1LoadBalancerVirtualServersIdSoftDeleteRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v1LoadBalancerVirtualServersIdSoftDelete(requestParameters: V1LoadBalancerVirtualServersIdSoftDeleteRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1LoadBalancerVirtualServersIdSoftDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<any>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(id))}/soft`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create one LoadBalancerVirtualServer
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersPost(requestParameters: V1LoadBalancerVirtualServersPostRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersPost(requestParameters: V1LoadBalancerVirtualServersPostRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersPost(requestParameters: V1LoadBalancerVirtualServersPostRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersPost(requestParameters: V1LoadBalancerVirtualServersPostRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const loadBalancerVirtualServer = requestParameters.loadBalancerVirtualServer;
        if (loadBalancerVirtualServer === null || loadBalancerVirtualServer === undefined) {
            throw new Error('Required parameter loadBalancerVirtualServer was null or undefined when calling v1LoadBalancerVirtualServersPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers`,
            loadBalancerVirtualServer,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Remove iRule from Load Balancer Virtual Server
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDelete(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDeleteRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDelete(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDeleteRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDelete(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDeleteRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDelete(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDeleteRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const virtualServerId = requestParameters.virtualServerId;
        if (virtualServerId === null || virtualServerId === undefined) {
            throw new Error('Required parameter virtualServerId was null or undefined when calling v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDelete.');
        }
        const iruleId = requestParameters.iruleId;
        if (iruleId === null || iruleId === undefined) {
            throw new Error('Required parameter iruleId was null or undefined when calling v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(virtualServerId))}/irules/${encodeURIComponent(String(iruleId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add iRule to Load Balancer Virtual Server
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPost(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPostRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPost(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPostRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPost(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPostRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPost(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPostRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const virtualServerId = requestParameters.virtualServerId;
        if (virtualServerId === null || virtualServerId === undefined) {
            throw new Error('Required parameter virtualServerId was null or undefined when calling v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPost.');
        }
        const iruleId = requestParameters.iruleId;
        if (iruleId === null || iruleId === undefined) {
            throw new Error('Required parameter iruleId was null or undefined when calling v1LoadBalancerVirtualServersVirtualServerIdIrulesIruleIdPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.post<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(virtualServerId))}/irules/${encodeURIComponent(String(iruleId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Remove Profile from Load Balancer Virtual Server
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDelete(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDeleteRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDelete(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDeleteRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDelete(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDeleteRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDelete(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDeleteRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const virtualServerId = requestParameters.virtualServerId;
        if (virtualServerId === null || virtualServerId === undefined) {
            throw new Error('Required parameter virtualServerId was null or undefined when calling v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDelete.');
        }
        const profileId = requestParameters.profileId;
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(virtualServerId))}/profiles/${encodeURIComponent(String(profileId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add Profile to Load Balancer Virtual Server
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPost(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPostRequestParams, observe?: 'body', reportProgress?: boolean): Observable<LoadBalancerVirtualServer>;
    public v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPost(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPostRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPost(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPostRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoadBalancerVirtualServer>>;
    public v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPost(requestParameters: V1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPostRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const virtualServerId = requestParameters.virtualServerId;
        if (virtualServerId === null || virtualServerId === undefined) {
            throw new Error('Required parameter virtualServerId was null or undefined when calling v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPost.');
        }
        const profileId = requestParameters.profileId;
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling v1LoadBalancerVirtualServersVirtualServerIdProfilesProfileIdPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.post<LoadBalancerVirtualServer>(`${this.configuration.basePath}/v1/load-balancer/virtual-servers/${encodeURIComponent(String(virtualServerId))}/profiles/${encodeURIComponent(String(profileId))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
