/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { Vlan } from '../model/vlan';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


export interface V1TiersTierIdVlansGetRequestParams {
    tierId: string;
    fields?: string;
    filter?: string;
    or?: string;
    sort?: string;
    join?: string;
    perPage?: number;
    offset?: number;
    page?: number;
    cache?: number;
}

export interface V1TiersTierIdVlansIdGetRequestParams {
    id: string;
    tierId: string;
    fields?: string;
    join?: string;
    cache?: number;
}


@Injectable({
  providedIn: 'root'
})
export class V1VlansService {

    protected basePath = 'http://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Retrieve many Vlan
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1TiersTierIdVlansGet(requestParameters: V1TiersTierIdVlansGetRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<Vlan>>;
    public v1TiersTierIdVlansGet(requestParameters: V1TiersTierIdVlansGetRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Vlan>>>;
    public v1TiersTierIdVlansGet(requestParameters: V1TiersTierIdVlansGetRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Vlan>>>;
    public v1TiersTierIdVlansGet(requestParameters: V1TiersTierIdVlansGetRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const tierId = requestParameters.tierId;
        if (tierId === null || tierId === undefined) {
            throw new Error('Required parameter tierId was null or undefined when calling v1TiersTierIdVlansGet.');
        }
        const fields = requestParameters.fields;
        const filter = requestParameters.filter;
        const or = requestParameters.or;
        const sort = requestParameters.sort;
        const join = requestParameters.join;
        const perPage = requestParameters.perPage;
        const offset = requestParameters.offset;
        const page = requestParameters.page;
        const cache = requestParameters.cache;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }
        if (or !== undefined && or !== null) {
            queryParameters = queryParameters.set('or', <any>or);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join', <any>join);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page', <any>perPage);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache', <any>cache);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<Vlan>>(`${this.configuration.basePath}/v1/tiers/${encodeURIComponent(String(tierId))}/vlans`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one Vlan
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1TiersTierIdVlansIdGet(requestParameters: V1TiersTierIdVlansIdGetRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Vlan>;
    public v1TiersTierIdVlansIdGet(requestParameters: V1TiersTierIdVlansIdGetRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Vlan>>;
    public v1TiersTierIdVlansIdGet(requestParameters: V1TiersTierIdVlansIdGetRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Vlan>>;
    public v1TiersTierIdVlansIdGet(requestParameters: V1TiersTierIdVlansIdGetRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1TiersTierIdVlansIdGet.');
        }
        const tierId = requestParameters.tierId;
        if (tierId === null || tierId === undefined) {
            throw new Error('Required parameter tierId was null or undefined when calling v1TiersTierIdVlansIdGet.');
        }
        const fields = requestParameters.fields;
        const join = requestParameters.join;
        const cache = requestParameters.cache;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join', <any>join);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache', <any>cache);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Vlan>(`${this.configuration.basePath}/v1/tiers/${encodeURIComponent(String(tierId))}/vlans/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
