/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { GeneratedVmwareNetworkAdapterBulkDto } from '../model/generatedVmwareNetworkAdapterBulkDto';
import { VmwareNetworkAdapter } from '../model/vmwareNetworkAdapter';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


export interface V1VmwareNetworkAdapterBulkPostRequestParams {
    generatedVmwareNetworkAdapterBulkDto: GeneratedVmwareNetworkAdapterBulkDto;
}

export interface V1VmwareNetworkAdapterGetRequestParams {
    fields?: string;
    filter?: string;
    or?: string;
    sort?: string;
    join?: string;
    perPage?: number;
    offset?: number;
    page?: number;
    cache?: number;
}

export interface V1VmwareNetworkAdapterIdDeleteRequestParams {
    id: string;
}

export interface V1VmwareNetworkAdapterIdGetRequestParams {
    id: string;
    fields?: string;
    join?: string;
    cache?: number;
}

export interface V1VmwareNetworkAdapterIdPatchRequestParams {
    id: string;
    vmwareNetworkAdapter: VmwareNetworkAdapter;
}

export interface V1VmwareNetworkAdapterIdPutRequestParams {
    id: string;
    vmwareNetworkAdapter: VmwareNetworkAdapter;
}

export interface V1VmwareNetworkAdapterIdRestorePatchRequestParams {
    id: string;
}

export interface V1VmwareNetworkAdapterIdSoftDeleteRequestParams {
    id: string;
}

export interface V1VmwareNetworkAdapterPostRequestParams {
    vmwareNetworkAdapter: VmwareNetworkAdapter;
}


@Injectable({
  providedIn: 'root'
})
export class V1VmwareNetworkAdapterService {

    protected basePath = 'http://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Create many VmwareNetworkAdapter
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterBulkPost(requestParameters: V1VmwareNetworkAdapterBulkPostRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterBulkPost(requestParameters: V1VmwareNetworkAdapterBulkPostRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<VmwareNetworkAdapter>>>;
    public v1VmwareNetworkAdapterBulkPost(requestParameters: V1VmwareNetworkAdapterBulkPostRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<VmwareNetworkAdapter>>>;
    public v1VmwareNetworkAdapterBulkPost(requestParameters: V1VmwareNetworkAdapterBulkPostRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const generatedVmwareNetworkAdapterBulkDto = requestParameters.generatedVmwareNetworkAdapterBulkDto;
        if (generatedVmwareNetworkAdapterBulkDto === null || generatedVmwareNetworkAdapterBulkDto === undefined) {
            throw new Error('Required parameter generatedVmwareNetworkAdapterBulkDto was null or undefined when calling v1VmwareNetworkAdapterBulkPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<VmwareNetworkAdapter>>(`${this.configuration.basePath}/v1/vmware/network-adapter/bulk`,
            generatedVmwareNetworkAdapterBulkDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve many VmwareNetworkAdapter
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterGet(requestParameters: V1VmwareNetworkAdapterGetRequestParams, observe?: 'body', reportProgress?: boolean): Observable<Array<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterGet(requestParameters: V1VmwareNetworkAdapterGetRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<VmwareNetworkAdapter>>>;
    public v1VmwareNetworkAdapterGet(requestParameters: V1VmwareNetworkAdapterGetRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<VmwareNetworkAdapter>>>;
    public v1VmwareNetworkAdapterGet(requestParameters: V1VmwareNetworkAdapterGetRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const fields = requestParameters.fields;
        const filter = requestParameters.filter;
        const or = requestParameters.or;
        const sort = requestParameters.sort;
        const join = requestParameters.join;
        const perPage = requestParameters.perPage;
        const offset = requestParameters.offset;
        const page = requestParameters.page;
        const cache = requestParameters.cache;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }
        if (or !== undefined && or !== null) {
            queryParameters = queryParameters.set('or', <any>or);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join', <any>join);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page', <any>perPage);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache', <any>cache);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<VmwareNetworkAdapter>>(`${this.configuration.basePath}/v1/vmware/network-adapter`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete one VmwareNetworkAdapter
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterIdDelete(requestParameters: V1VmwareNetworkAdapterIdDeleteRequestParams, observe?: 'body', reportProgress?: boolean): Observable<VmwareNetworkAdapter>;
    public v1VmwareNetworkAdapterIdDelete(requestParameters: V1VmwareNetworkAdapterIdDeleteRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterIdDelete(requestParameters: V1VmwareNetworkAdapterIdDeleteRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterIdDelete(requestParameters: V1VmwareNetworkAdapterIdDeleteRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1VmwareNetworkAdapterIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<VmwareNetworkAdapter>(`${this.configuration.basePath}/v1/vmware/network-adapter/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve one VmwareNetworkAdapter
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterIdGet(requestParameters: V1VmwareNetworkAdapterIdGetRequestParams, observe?: 'body', reportProgress?: boolean): Observable<VmwareNetworkAdapter>;
    public v1VmwareNetworkAdapterIdGet(requestParameters: V1VmwareNetworkAdapterIdGetRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterIdGet(requestParameters: V1VmwareNetworkAdapterIdGetRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterIdGet(requestParameters: V1VmwareNetworkAdapterIdGetRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1VmwareNetworkAdapterIdGet.');
        }
        const fields = requestParameters.fields;
        const join = requestParameters.join;
        const cache = requestParameters.cache;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields', <any>fields);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join', <any>join);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache', <any>cache);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<VmwareNetworkAdapter>(`${this.configuration.basePath}/v1/vmware/network-adapter/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update one VmwareNetworkAdapter
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterIdPatch(requestParameters: V1VmwareNetworkAdapterIdPatchRequestParams, observe?: 'body', reportProgress?: boolean): Observable<VmwareNetworkAdapter>;
    public v1VmwareNetworkAdapterIdPatch(requestParameters: V1VmwareNetworkAdapterIdPatchRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterIdPatch(requestParameters: V1VmwareNetworkAdapterIdPatchRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterIdPatch(requestParameters: V1VmwareNetworkAdapterIdPatchRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1VmwareNetworkAdapterIdPatch.');
        }
        const vmwareNetworkAdapter = requestParameters.vmwareNetworkAdapter;
        if (vmwareNetworkAdapter === null || vmwareNetworkAdapter === undefined) {
            throw new Error('Required parameter vmwareNetworkAdapter was null or undefined when calling v1VmwareNetworkAdapterIdPatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<VmwareNetworkAdapter>(`${this.configuration.basePath}/v1/vmware/network-adapter/${encodeURIComponent(String(id))}`,
            vmwareNetworkAdapter,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Replace one VmwareNetworkAdapter
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterIdPut(requestParameters: V1VmwareNetworkAdapterIdPutRequestParams, observe?: 'body', reportProgress?: boolean): Observable<VmwareNetworkAdapter>;
    public v1VmwareNetworkAdapterIdPut(requestParameters: V1VmwareNetworkAdapterIdPutRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterIdPut(requestParameters: V1VmwareNetworkAdapterIdPutRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterIdPut(requestParameters: V1VmwareNetworkAdapterIdPutRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1VmwareNetworkAdapterIdPut.');
        }
        const vmwareNetworkAdapter = requestParameters.vmwareNetworkAdapter;
        if (vmwareNetworkAdapter === null || vmwareNetworkAdapter === undefined) {
            throw new Error('Required parameter vmwareNetworkAdapter was null or undefined when calling v1VmwareNetworkAdapterIdPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<VmwareNetworkAdapter>(`${this.configuration.basePath}/v1/vmware/network-adapter/${encodeURIComponent(String(id))}`,
            vmwareNetworkAdapter,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restores a Soft-Deleted Entity.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterIdRestorePatch(requestParameters: V1VmwareNetworkAdapterIdRestorePatchRequestParams, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v1VmwareNetworkAdapterIdRestorePatch(requestParameters: V1VmwareNetworkAdapterIdRestorePatchRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v1VmwareNetworkAdapterIdRestorePatch(requestParameters: V1VmwareNetworkAdapterIdRestorePatchRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v1VmwareNetworkAdapterIdRestorePatch(requestParameters: V1VmwareNetworkAdapterIdRestorePatchRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1VmwareNetworkAdapterIdRestorePatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.patch<any>(`${this.configuration.basePath}/v1/vmware/network-adapter/${encodeURIComponent(String(id))}/restore`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Soft deletes an Entity.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterIdSoftDelete(requestParameters: V1VmwareNetworkAdapterIdSoftDeleteRequestParams, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public v1VmwareNetworkAdapterIdSoftDelete(requestParameters: V1VmwareNetworkAdapterIdSoftDeleteRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public v1VmwareNetworkAdapterIdSoftDelete(requestParameters: V1VmwareNetworkAdapterIdSoftDeleteRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public v1VmwareNetworkAdapterIdSoftDelete(requestParameters: V1VmwareNetworkAdapterIdSoftDeleteRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling v1VmwareNetworkAdapterIdSoftDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<any>(`${this.configuration.basePath}/v1/vmware/network-adapter/${encodeURIComponent(String(id))}/soft`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create one VmwareNetworkAdapter
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v1VmwareNetworkAdapterPost(requestParameters: V1VmwareNetworkAdapterPostRequestParams, observe?: 'body', reportProgress?: boolean): Observable<VmwareNetworkAdapter>;
    public v1VmwareNetworkAdapterPost(requestParameters: V1VmwareNetworkAdapterPostRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterPost(requestParameters: V1VmwareNetworkAdapterPostRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<VmwareNetworkAdapter>>;
    public v1VmwareNetworkAdapterPost(requestParameters: V1VmwareNetworkAdapterPostRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const vmwareNetworkAdapter = requestParameters.vmwareNetworkAdapter;
        if (vmwareNetworkAdapter === null || vmwareNetworkAdapter === undefined) {
            throw new Error('Required parameter vmwareNetworkAdapter was null or undefined when calling v1VmwareNetworkAdapterPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<VmwareNetworkAdapter>(`${this.configuration.basePath}/v1/vmware/network-adapter`,
            vmwareNetworkAdapter,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
