/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditLog { 
    id: string;
    actionType: AuditLogActionTypeEnum;
    entityType: AuditLogEntityTypeEnum;
    entityBefore?: object;
    entityAfter?: object;
    changedProperties?: Array<string>;
    readonly timestamp: string;
    changedBy: string;
    groupName?: string;
    datacenterId: string;
    tierId?: string;
}
export enum AuditLogActionTypeEnum {
    BulkUpload = 'BulkUpload',
    Create = 'Create',
    Update = 'Update',
    SoftDelete = 'SoftDelete',
    Restore = 'Restore',
    Delete = 'Delete',
    Deploy = 'Deploy'
};
export enum AuditLogEntityTypeEnum {
    Appliance = 'Appliance',
    Datacenter = 'Datacenter',
    Job = 'Job',
    ProvisionTier = 'provision-tier',
    ProvisionTierNetworkSecurity = 'provision-tier-network-security',
    LoadBalancerHealthMonitor = 'LoadBalancerHealthMonitor',
    LoadBalancerIrule = 'LoadBalancerIrule',
    LoadBalancerNode = 'LoadBalancerNode',
    LoadBalancerProfile = 'LoadBalancerProfile',
    LoadBalancerPolicy = 'LoadBalancerPolicy',
    LoadBalancerRoute = 'LoadBalancerRoute',
    LoadBalancerPool = 'LoadBalancerPool',
    LoadBalancerSelfIp = 'LoadBalancerSelfIp',
    LoadBalancerVirtualServer = 'LoadBalancerVirtualServer',
    LoadBalancerVlan = 'LoadBalancerVlan',
    PhysicalServer = 'PhysicalServer',
    NetworkObject = 'NetworkObject',
    NetworkObjectGroup = 'NetworkObjectGroup',
    ServiceObject = 'ServiceObject',
    ServiceObjectGroup = 'ServiceObjectGroup',
    StaticRoute = 'StaticRoute',
    FirewallRule = 'FirewallRule',
    NatRule = 'NatRule',
    Subnet = 'Subnet',
    Vlan = 'Vlan',
    Tier = 'Tier'
};



