/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExternalRoute { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly version?: number;
    description?: string;
    externalRouteIp: string;
    vrf: ExternalRouteVrfEnum;
    environment: ExternalRouteEnvironmentEnum;
    wanFormId: string;
}
export enum ExternalRouteVrfEnum {
    Appprod = 'appprod',
    Appdev = 'appdev',
    Dataprod = 'dataprod',
    Datadev = 'datadev',
    Edcmgmt = 'edcmgmt',
    Transport = 'transport'
};
export enum ExternalRouteEnvironmentEnum {
    Prod = 'prod',
    Dev = 'dev',
    Val = 'val',
    Imp = 'imp'
};



