/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { L3Out } from './l3Out';
import { Tenant } from './tenant';
import { ExternalVrfConnection } from './externalVrfConnection';


export interface ExternalFirewall { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly version?: number;
    readonly deletedAt?: string;
    readonly provisionedAt?: string;
    readonly provisionedVersion?: number;
    name?: string;
    firewallDeviceType?: string;
    vsysName: string;
    readonly externalVrfConnections?: Array<ExternalVrfConnection>;
    uniqueZonePerExternalVrfConnection?: boolean;
    readonly l3outs?: L3Out;
    readonly tenant?: Tenant;
    tenantId?: string;
    bgpAsn?: number;
    routingCost?: number;
}

