/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { F5RuntimeProfile } from './f5RuntimeProfile';


export interface F5RuntimeProfilesReference { 
    /**
     * Array of profiles
     */
    readonly items: Array<F5RuntimeProfile>;
}

