/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { F5RuntimeHostInfoAvailability } from './f5RuntimeHostInfoAvailability';


export interface F5RuntimeHostInfo { 
    /**
     * Hostname of the F5 device
     */
    readonly hostname: string;
    /**
     * Software version of the F5 device
     */
    readonly softwareVersion: string;
    availability: F5RuntimeHostInfoAvailability;
}

