/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadBalancerIrule } from './loadBalancerIrule';
import { LoadBalancerProfile } from './loadBalancerProfile';
import { LoadBalancerPolicy } from './loadBalancerPolicy';
import { LoadBalancerPool } from './loadBalancerPool';


export interface LoadBalancerVirtualServer { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly version?: number;
    readonly deletedAt?: string;
    readonly provisionedAt?: string;
    readonly provisionedVersion?: number;
    name: string;
    description?: string;
    sourceIpAddress: string;
    destinationIpAddress: string;
    defaultPoolId?: string;
    readonly defaultPool?: LoadBalancerPool;
    readonly profiles?: Array<LoadBalancerProfile>;
    readonly policies?: Array<LoadBalancerPolicy>;
    readonly irules?: Array<LoadBalancerIrule>;
    sourceAddressTranslation: LoadBalancerVirtualServerSourceAddressTranslationEnum;
    type: LoadBalancerVirtualServerTypeEnum;
    servicePort: number;
    tierId: string;
}
export enum LoadBalancerVirtualServerSourceAddressTranslationEnum {
    None = 'None',
    AutoMap = 'AutoMap',
    Snat = 'SNAT'
};
export enum LoadBalancerVirtualServerTypeEnum {
    Standard = 'Standard'
};



