/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NodeConnectivity { 
    /**
     * External VRFs this node can reach
     */
    reachableExternalVrfs: Array<string>;
    /**
     * External VRFs that can reach this node
     */
    advertisableToExternalVrfs: Array<string>;
    /**
     * Other VRFs this node can communicate with
     */
    connectedVrfs: Array<string>;
    /**
     * Whether this node provides default routing
     */
    providesDefaultRoute: boolean;
    /**
     * Whether this node can receive external routes
     */
    canReceiveExternalRoutes: boolean;
}

