/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PathInfo } from './pathInfo';


export interface PathResult { 
    /**
     * Version of the graph used to calculate the path
     */
    graphTenantVersion: number;
    /**
     * Data plane path (infrastructure/physical connectivity)
     */
    dataPath: PathInfo;
    /**
     * Control plane path (policy/contract connectivity)
     */
    controlPath: PathInfo;
    /**
     * Traversal scope
     */
    traversalScope: string;
    /**
     * Whether all control plane checks passed (true = allowed, false = denied, undefined = not yet evaluated)
     */
    controlPlaneAllowed?: boolean;
    /**
     * Adjacency list used for path calculation (debug info)
     */
    adjacencyList?: object;
    /**
     * Whether the query is outdated (tenant version changed)
     */
    queryOutdated?: boolean;
}

