/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
import { BridgeDomain } from './bridgeDomain';


export interface RouteProfile { 
    readonly id?: string;
    name?: string;
    alias?: string;
    description?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly deletedAt?: string;
    readonly provisionedAt?: string;
    readonly bridgeDomains?: Array<BridgeDomain>;
    readonly tenant?: Tenant;
    tenantId: string;
}

