/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SelfService { 
    id: string;
    rawConfigType: string | null;
    rawXMLConfig: object | null;
    rawTextConfig: string | null;
    rawJsonConfig: object | null;
    mappedObjects: object | null;
    intervrfSubnets: string | null;
    convertedConfig: object | null;
    datacenterId: string | null;
}

