/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceObject } from './serviceObject';


export interface ServiceObjectGroup { 
    readonly id?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    readonly version?: number;
    readonly tenantVersion?: number;
    readonly deletedAt?: string;
    readonly provisionedAt?: string;
    readonly provisionedVersion?: number;
    name: string;
    description?: string;
    type: ServiceObjectGroupTypeEnum;
    readonly serviceObjects?: Array<ServiceObject>;
    tierId: string;
}
export enum ServiceObjectGroupTypeEnum {
    Tcp = 'TCP',
    Udp = 'UDP',
    Tcpudp = 'TCPUDP'
};



