/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimplifiedExternalRoute } from './simplifiedExternalRoute';
import { SimplifiedInternalRoute } from './simplifiedInternalRoute';


export interface SimplifiedWanForm { 
    id: string;
    status: string;
    internalRoutes: Array<SimplifiedInternalRoute>;
    externalRoutes: Array<SimplifiedExternalRoute>;
}

