/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TenantCatalogItem { 
    /**
     * Tenant name
     */
    tenant: string;
    /**
     * Tenant database
     */
    tenantDatabase: string;
    /**
     * Tenant query parameter
     */
    tenantQueryParameter: string;
    /**
     * Tenant full name
     */
    tenantFullName: string;
    /**
     * Ansible service config
     */
    ansible: object;
    /**
     * Actifio service config
     */
    actifio: object;
}

