/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkflowValidationError { 
    type: WorkflowValidationErrorTypeEnum;
    /**
     * The context of the error
     */
    context: object;
}
export enum WorkflowValidationErrorTypeEnum {
    ModuleMissing = 'MODULE_MISSING',
    ModuleUnexpected = 'MODULE_UNEXPECTED',
    ModuleConfigMissing = 'MODULE_CONFIG_MISSING',
    AuditLogRuleMissing = 'AUDIT_LOG_RULE_MISSING',
    ResourceMatchMissing = 'RESOURCE_MATCH_MISSING',
    ActionMismatch = 'ACTION_MISMATCH',
    PropertyValidation = 'PROPERTY_VALIDATION',
    PropertyMapMissing = 'PROPERTY_MAP_MISSING',
    IdComparison = 'ID_COMPARISON',
    UnmatchedTerraformChange = 'UNMATCHED_TERRAFORM_CHANGE'
};



