/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActifioAddApplicationsToClusterDto } from './actifioAddApplicationsToClusterDto';


export interface ActifioAddApplicationsDto { 
    hostId: string;
    clusters: Array<ActifioAddApplicationsToClusterDto>;
}

