/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfigurationUpload { 
    readonly id?: string;
    createdAt?: object;
    updatedAt?: object;
    readonly version?: number;
    deletedAt?: object;
    provisionedAt?: object;
    readonly provisionedVersion?: number;
    requestedAt: object;
    configuredAt?: object;
    type: ConfigurationUploadType;
    file: object;
    configuration: object;
}
export enum ConfigurationUploadType {
    OS = 'OS',
    VM = 'VM'
};



