/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoadBalancerNode {
    readonly id?: string;
    createdAt?: object;
    updatedAt?: object;
    readonly version?: number;
    deletedAt?: object;
    provisionedAt?: object;
    readonly provisionedVersion?: number;
    name: string;
    description?: string;
    type: LoadBalancerNodeType;
    servicePort: number;
    ipAddress: string;
    fqdn: string;
    autoPopulate: boolean;
    tierId: string;
}
export enum LoadBalancerNodeType {
    IpAddress = 'IpAddress',
    Fqdn = 'Fqdn'
};



