/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadBalancerNode } from './loadBalancerNode';
import { LoadBalancerHealthMonitor } from './loadBalancerHealthMonitor';


export interface LoadBalancerPool { 
    readonly id?: string;
    createdAt?: object;
    updatedAt?: object;
    readonly version?: number;
    deletedAt?: object;
    provisionedAt?: object;
    readonly provisionedVersion?: number;
    name: string;
    description?: string;
    loadBalancingMethod: LoadBalancerPoolLoadBalancingMethod;
    nodes?: Array<LoadBalancerNode>;
    healthMonitors?: Array<LoadBalancerHealthMonitor>;
    servicePort: number;
    tierId: string;
}
export enum LoadBalancerPoolLoadBalancingMethod {
    RoundRobin = 'RoundRobin',
    LeastSessions = 'LeastSessions',
    FastestNode = 'FastestNode',
    FastestAppResponse = 'FastestAppResponse'
};



