/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NetworkObject } from './networkObject';
import { ServiceObject } from './serviceObject';
import { NetworkObjectGroup } from './networkObjectGroup';


export interface NatRule { 
    readonly id?: string;
    createdAt?: object;
    updatedAt?: object;
    readonly version?: number;
    deletedAt?: object;
    name: string;
    description?: string;
    enabled: boolean;
    ruleIndex: number;
    translationType: NatRuleTranslationType;
    direction: NatRuleDirection;
    biDirectional: boolean;
    originalSourceAddressType: NatRuleOriginalSourceAddressType;
    translatedSourceAddressType: NatRuleTranslatedSourceAddressType;
    originalDestinationAddressType: NatRuleOriginalDestinationAddressType;
    translatedDestinationAddressType: NatRuleTranslatedDestinationAddressType;
    originalServiceType: NatRuleOriginalServiceType;
    translatedServiceType: NatRuleTranslatedServiceType;
    natRuleGroupId: string;
    originalSourceNetworkObjectId?: string;
    originalSourceNetworkObjectGroupId?: string;
    translatedSourceNetworkObjectId?: string;
    translatedSourceNetworkObjectGroupId?: string;
    originalDestinationNetworkObjectId?: string;
    originalDestinationNetworkObjectGroupId?: string;
    translatedDestinationNetworkObjectId?: string;
    translatedDestinationNetworkObjectGroupId?: string;
    originalServiceObjectId?: string;
    translatedServiceObjectId?: string;
    originalSourceNetworkObject?: NetworkObject & object;
    originalSourceNetworkObjectGroup?: NetworkObjectGroup & object;
    translatedSourceNetworkObject?: NetworkObject & object;
    translatedSourceNetworkObjectGroup?: NetworkObjectGroup & object;
    originalDestinationNetworkObject?: NetworkObject & object;
    originalDestinationNetworkObjectGroup?: NetworkObjectGroup & object;
    translatedDestinationNetworkObject?: NetworkObject & object;
    translatedDestinationNetworkObjectGroup?: NetworkObjectGroup & object;
    originalServiceObject?: ServiceObject & object;
    translatedServiceObject?: ServiceObject & object;
}
export enum NatRuleTranslationType {
    None = 'None',
    Static = 'Static',
    DynamicIp = 'DynamicIp',
    DynamicIpAndPort = 'DynamicIpAndPort'
};
export enum NatRuleDirection {
    In = 'In',
    Out = 'Out'
};
export enum NatRuleOriginalSourceAddressType {
    None = 'None',
    NetworkObject = 'NetworkObject',
    NetworkObjectGroup = 'NetworkObjectGroup'
};
export enum NatRuleTranslatedSourceAddressType {
    None = 'None',
    NetworkObject = 'NetworkObject',
    NetworkObjectGroup = 'NetworkObjectGroup'
};
export enum NatRuleOriginalDestinationAddressType {
    None = 'None',
    NetworkObject = 'NetworkObject',
    NetworkObjectGroup = 'NetworkObjectGroup'
};
export enum NatRuleTranslatedDestinationAddressType {
    None = 'None',
    NetworkObject = 'NetworkObject',
    NetworkObjectGroup = 'NetworkObjectGroup'
};
export enum NatRuleOriginalServiceType {
    None = 'None',
    ServiceObject = 'ServiceObject'
};
export enum NatRuleTranslatedServiceType {
    None = 'None',
    ServiceObject = 'ServiceObject'
};



