/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadBalancerVirtualServer } from './loadBalancerVirtualServer';
import { StaticRoute } from './staticRoute';
import { LoadBalancerIrule } from './loadBalancerIrule';
import { LoadBalancerNode } from './loadBalancerNode';
import { LoadBalancerHealthMonitor } from './loadBalancerHealthMonitor';
import { Vlan } from './vlan';
import { LoadBalancerPool } from './loadBalancerPool';
import { ServiceObjectGroup } from './serviceObjectGroup';
import { NetworkObject } from './networkObject';
import { ServiceObject } from './serviceObject';
import { NetworkObjectGroup } from './networkObjectGroup';
import { FirewallRuleGroup } from './firewallRuleGroup';
import { Subnet } from './subnet';


export interface Tier { 
    readonly id?: string;
    createdAt?: object;
    updatedAt?: object;
    readonly version?: number;
    deletedAt?: object;
    provisionedAt?: object;
    readonly provisionedVersion?: number;
    name: string;
    description?: string;
    datacenterId: string;
    readonly vlans?: Array<Vlan>;
    readonly subnets?: Array<Subnet>;
    readonly staticRoutes?: Array<StaticRoute>;
    readonly firewallRuleGroups?: Array<FirewallRuleGroup>;
    readonly networkObjects?: Array<NetworkObject>;
    readonly networkObjectGroups?: Array<NetworkObjectGroup>;
    readonly serviceObjects?: Array<ServiceObject>;
    readonly serviceObjectGroups?: Array<ServiceObjectGroup>;
    readonly loadBalancerIrules?: Array<LoadBalancerIrule>;
    readonly loadBalancerNodes?: Array<LoadBalancerNode>;
    readonly loadBalancerPools?: Array<LoadBalancerPool>;
    readonly loadBalancerHealthMonitors?: Array<LoadBalancerHealthMonitor>;
    readonly loadBalancerVirtualServers?: Array<LoadBalancerVirtualServer>;
}

