/**
 * Draas
 * Draas OAS Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { Appliance } from '../model/appliance';
import { GeneratedApplianceBulkDto } from '../model/generatedApplianceBulkDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class AppliancesService {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Create many Appliance
     * @param generatedApplianceBulkDto Generated Appliance bulk DTO.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesBulkPost(generatedApplianceBulkDto: GeneratedApplianceBulkDto, observe?: 'body', reportProgress?: boolean): Observable<Array<Appliance>>;
    public appliancesBulkPost(generatedApplianceBulkDto: GeneratedApplianceBulkDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Appliance>>>;
    public appliancesBulkPost(generatedApplianceBulkDto: GeneratedApplianceBulkDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Appliance>>>;
    public appliancesBulkPost(generatedApplianceBulkDto: GeneratedApplianceBulkDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (generatedApplianceBulkDto === null || generatedApplianceBulkDto === undefined) {
            throw new Error('Required parameter generatedApplianceBulkDto was null or undefined when calling appliancesBulkPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<Appliance>>(`${this.configuration.basePath}/appliances/bulk`,
            generatedApplianceBulkDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * Retrieve many Appliance
     * @param fields Selects fields that should be returned in the reponse body.
     * @param filter Adds fields request condition (multiple conditions) to the request.
     * @param or Adds OR conditions to the request.
     * @param sort Adds sort by field (by multiple fields) and order to query result.
     * @param join Receive joined relational objects in GET result (with all or selected fields).
     * @param perPage Receive amount of entities.
     * @param offset Offset amount of entities.
     * @param page Receive a portion of limit.
     * @param cache Reset cache (if was enabled) and receive entities from the DB.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesGet(fields?: string, filter?: string, or?: string, sort?: string, join?: string, perPage?: number, offset?: number, page?: number, cache?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Appliance>>;
    public appliancesGet(fields?: string, filter?: string, or?: string, sort?: string, join?: string, perPage?: number, offset?: number, page?: number, cache?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Appliance>>>;
    public appliancesGet(fields?: string, filter?: string, or?: string, sort?: string, join?: string, perPage?: number, offset?: number, page?: number, cache?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Appliance>>>;
    public appliancesGet(fields?: string, filter?: string, or?: string, sort?: string, join?: string, perPage?: number, offset?: number, page?: number, cache?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields',  fields as any);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter',  filter as any);
        }
        if (or !== undefined && or !== null) {
            queryParameters = queryParameters.set('or',  or as any);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort',  sort as any);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join',  join as any);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page',  perPage as any);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset',  offset as any);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page',  page as any);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache',  cache as any);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<Appliance>>(`${this.configuration.basePath}/appliances`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * Delete one Appliance
     * @param id Appliance UUID.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesIdDelete(id: string, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public appliancesIdDelete(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public appliancesIdDelete(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public appliancesIdDelete(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling appliancesIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<Appliance>(`${this.configuration.basePath}/appliances/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * Retrieve one Appliance
     * @param id Appliance UUID.
     * @param fields Selects fields that should be returned in the reponse body.
     * @param join Receive joined relational objects in GET result (with all or selected fields).
     * @param cache Reset cache (if was enabled) and receive entities from the DB.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesIdGet(id: string, fields?: string, join?: string, cache?: number, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public appliancesIdGet(id: string, fields?: string, join?: string, cache?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public appliancesIdGet(id: string, fields?: string, join?: string, cache?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public appliancesIdGet(id: string, fields?: string, join?: string, cache?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling appliancesIdGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (fields !== undefined && fields !== null) {
            queryParameters = queryParameters.set('fields',  fields as any);
        }
        if (join !== undefined && join !== null) {
            queryParameters = queryParameters.set('join',  join as any);
        }
        if (cache !== undefined && cache !== null) {
            queryParameters = queryParameters.set('cache',  cache as any);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Appliance>(`${this.configuration.basePath}/appliances/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * Update one Appliance
     * @param id Appliance UUID.
     * @param appliance Appliance entity.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesIdPatch(id: string, appliance: Appliance, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public appliancesIdPatch(id: string, appliance: Appliance, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public appliancesIdPatch(id: string, appliance: Appliance, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public appliancesIdPatch(id: string, appliance: Appliance, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling appliancesIdPatch.');
        }
        if (appliance === null || appliance === undefined) {
            throw new Error('Required parameter appliance was null or undefined when calling appliancesIdPatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<Appliance>(`${this.configuration.basePath}/appliances/${encodeURIComponent(String(id))}`,
            appliance,
            {
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * Replace one Appliance
     * @param id Appliance UUID.
     * @param appliance Appliance entity.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesIdPut(id: string, appliance: Appliance, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public appliancesIdPut(id: string, appliance: Appliance, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public appliancesIdPut(id: string, appliance: Appliance, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public appliancesIdPut(id: string, appliance: Appliance, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling appliancesIdPut.');
        }
        if (appliance === null || appliance === undefined) {
            throw new Error('Required parameter appliance was null or undefined when calling appliancesIdPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Appliance>(`${this.configuration.basePath}/appliances/${encodeURIComponent(String(id))}`,
            appliance,
            {
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * Restores a Soft-Deleted Entity.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesIdRestorePatch(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public appliancesIdRestorePatch(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public appliancesIdRestorePatch(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public appliancesIdRestorePatch(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.patch<any>(`${this.configuration.basePath}/appliances/${encodeURIComponent(String(id))}/restore`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * Soft deletes an Entity.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesIdSoftDelete(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public appliancesIdSoftDelete(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public appliancesIdSoftDelete(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public appliancesIdSoftDelete(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<any>(`${this.configuration.basePath}/appliances/${encodeURIComponent(String(id))}/soft`,
            {
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * Create one Appliance
     * @param appliance Appliance entity.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appliancesPost(appliance: Appliance, observe?: 'body', reportProgress?: boolean): Observable<Appliance>;
    public appliancesPost(appliance: Appliance, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Appliance>>;
    public appliancesPost(appliance: Appliance, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Appliance>>;
    public appliancesPost(appliance: Appliance, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (appliance === null || appliance === undefined) {
            throw new Error('Required parameter appliance was null or undefined when calling appliancesPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Appliance>(`${this.configuration.basePath}/appliances`,
            appliance,
            {
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

}
